"""
Django settings for shop_game project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-fy%84j5(je@^=#-n%tvhhz(*+-72se49he+x1zza(099&9yc$u')

# SECURITY WARNING: don't run with debug turned on in production!
# CẢNH BÁO: CHỈ ĐỔI THÀNH False KHI BẠN CHUẨN BỊ UP LÊN HOSTING/VPS CHẠY THẬT.
# Nếu bạn đang chạy thử ở localhost (máy tính cá nhân), hãy cứ để True nhé.
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'
IS_RENDER = os.getenv('RENDER', '').lower() == 'true'
if IS_RENDER:
    DEBUG = False

# Khi DEBUG = False, bạn bắt buộc phải khai báo tên miền của bạn vào đây.
# Dấu '*' nghĩa là cho phép mọi tên miền truy cập.
ALLOWED_HOSTS = [h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',') if h.strip()]
RENDER_HOST = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
if RENDER_HOST and RENDER_HOST not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_HOST)


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop_game.accounts',
    'shop_game.shop',
    'shop_game.billing',
    'shop_game.minigame',
    'shop_game.core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # Kích hoạt hệ thống dịch (THÊM DÒNG NÀY)
    'django.middleware.locale.LocaleMiddleware', 
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'shop_game.core.middleware.MaintenanceModeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop_game.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop_game.core.context_processors.site_meta',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop_game.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=bool(os.getenv('DATABASE_URL')) and (not DEBUG),
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Cấu hình 2 ngôn ngữ hỗ trợ
LANGUAGES = [
    ('vi', 'Vietnamese'),
    ('en', 'English'),
]

# Thư mục chứa các file từ điển dịch (sẽ tạo ở Bước 4)
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGE_CODE = 'en-us'

# Sửa lại thành múi giờ Châu Á/Hồ Chí Minh
TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

# ĐỔI DÒNG NÀY THÀNH False ĐỂ LƯU GIỜ THỰC TẾ CỦA VN VÀO DATABASE
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Chỉ thêm STATICFILES_DIRS nếu directory thực sự tồn tại
_static_parent = BASE_DIR.parent / 'static'
if _static_parent.exists():
    STATICFILES_DIRS = [_static_parent]
else:
    STATICFILES_DIRS = []
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
if IS_RENDER:
    # Render: nếu đã gắn Persistent Disk thì dùng RENDER_DISK_PATH.
    # Nếu chưa gắn disk, lưu tạm trong /tmp (writable trên Render).
    render_disk_path = os.getenv('RENDER_DISK_PATH', '').strip()
    if render_disk_path:
        MEDIA_ROOT = Path(render_disk_path) / 'media'
    else:
        MEDIA_ROOT = Path('/tmp/media')
else:
    MEDIA_ROOT = BASE_DIR / 'media'

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

AUTH_USER_MODEL = 'accounts.CustomUser'

# Cấu hình nạp tiền ngân hàng bằng VietQR
BANK_QR_BANK_CODE = 'MB'
BANK_QR_ACCOUNT_NO = ''
BANK_QR_ACCOUNT_NAME = 'SHOPDH6'
# Nếu muốn dùng 1 ảnh QR cố định (ví dụ link CDN), điền URL tại đây hoặc env.
BANK_QR_STATIC_IMAGE_URL = os.getenv(
    'BANK_QR_STATIC_IMAGE_URL',
    'https://img.sanishtech.com/u/235b68e0b06f9e0cb62a355bbf1d798c.jpeg?zarsrc=30&utm_source=zalo&utm_medium=zalo&utm_campaign=zalolink'
)

# ==========================================
# CẤU HÌNH GIAO DIỆN ADMIN JAZZMIN
# ==========================================
JAZZMIN_SETTINGS = {
    "site_title": "Admin - ShopDH6",
    "site_header": "ShopDH6",
    "site_brand": "Quản Trị ShopDH6",
    "site_logo": None,
    "welcome_sign": "Chào mừng đến với hệ thống quản trị ShopDH6!",
    "copyright": "Bản quyền thuộc về ShopDH6",
    "search_model": ["accounts.CustomUser", "shop.AccountInventory"],
    "user_avatar": None,
    
    # Menu bên trái
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Sắp xếp thứ tự các App trên menu
    "order_with_respect_to": ["shop", "minigame", "billing", "core", "accounts"],

    # Gắn Icon cho từng bảng (Dùng FontAwesome 5)
    "icons": {
        "auth": "fas fa-users-cog",
        "accounts.CustomUser": "fas fa-user",
        "accounts.LoginHistory": "fas fa-history",
        "shop.GameCategory": "fas fa-gamepad",
        "shop.AccountInventory": "fas fa-box-open",
        "shop.NickOrder": "fas fa-shopping-cart",
        "billing.CardProvider": "fas fa-network-wired",
        "billing.CardInventory": "fas fa-credit-card",
        "billing.DepositTransaction": "fas fa-money-bill-wave",
        "minigame.Wheel": "fas fa-life-ring",
        "minigame.SpinHistory": "fas fa-sync",
        "core.SiteSetting": "fas fa-cogs",
        "core.Banner": "fas fa-images",
        "core.News": "fas fa-newspaper",
    },

    # Tùy chỉnh liên kết nhanh
    "custom_links": {
        "shop": [{
            "name": "Xem trang chủ Web",
            "url": "/",
            "icon": "fas fa-eye",
        }]
    },
}

# Đổi màu sắc giao diện (Sidebar tối màu)
JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark",
    "theme": "default",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "brand_small": False,
    "brand_colour": "navbar-white",
    "accent": "accent-primary",
    "sidebar_nav_small_text": False,
    "footer": "footer-dark",
    "pagination": "pagination-rounded",
}

# ==========================================
# CẤU HÌNH LOGGING ĐỂ DEBUG LỖI UPLOAD IMAGE
# ==========================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'shop_game': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Tạo logs directory nếu không tồn tại
logs_dir = BASE_DIR / 'logs'
if not logs_dir.exists():
    logs_dir.mkdir(exist_ok=True)

# ==========================================
# CẤU HÌNH FILE UPLOAD
# ==========================================
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644  # Quyền read-write cho owner, read cho others

