# Generated by Django 6.0.3 on 2026-03-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Tiêu đề')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Ảnh Banner')),
                ('link', models.CharField(blank=True, help_text='VD: /danh-muc/free-fire', max_length=255, verbose_name='Đường dẫn khi click')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Banner / Trình diễn ảnh',
                'verbose_name_plural': 'Banner / Trình diễn ảnh',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài viết')),
                ('slug', models.SlugField(unique=True, verbose_name='Đường dẫn SEO')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Ảnh đại diện')),
                ('content', models.TextField(verbose_name='Nội dung bài viết')),
                ('is_published', models.BooleanField(default=True, verbose_name='Xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Shop Game Siêu Rẻ', max_length=100, verbose_name='Tên Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo Website')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Favicon (Icon tab)')),
                ('currency', models.CharField(default='VNĐ', max_length=10, verbose_name='Tiền tệ')),
                ('hotline', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hotline hỗ trợ')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Link Facebook')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Bật lên để đóng web bảo trì', verbose_name='Chế độ bảo trì')),
            ],
            options={
                'verbose_name': 'Cấu hình Website',
                'verbose_name_plural': 'Cấu hình Website',
            },
        ),
    ]
