# Generated by Django 6.0.3 on 2026-04-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bank_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Ảnh QR nạp ngân hàng'),
        ),
    ]
