# Generated by Django 6.0.3 on 2026-03-25 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Game/Danh mục')),
                ('slug', models.SlugField(help_text='Ví dụ: lien-quan-mobile', max_length=100, unique=True, verbose_name='Đường dẫn (Slug)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Ảnh đại diện')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Danh mục Game',
                'verbose_name_plural': 'Danh mục Game',
            },
        ),
        migrations.CreateModel(
            name='AccountInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Tài khoản đăng nhập')),
                ('password', models.CharField(max_length=100, verbose_name='Mật khẩu')),
                ('login_method', models.CharField(default='Garena', help_text='VD: Facebook, Garena, Google...', max_length=50, verbose_name='Kiểu đăng nhập')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá bán')),
                ('rank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mức Rank')),
                ('details', models.TextField(blank=True, help_text='VD: Có nhiều skin súng VIP, đồ hiếm...', null=True, verbose_name='Thông tin nổi bật')),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to='accounts/thumbs/', verbose_name='Ảnh bìa nick')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='accounts/details/', verbose_name='Ảnh chi tiết 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='accounts/details/', verbose_name='Ảnh chi tiết 2')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Đang bán (Chưa ai mua)'), ('SOLD', 'Đã bán'), ('HIDDEN', 'Tạm ẩn')], default='AVAILABLE', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='shop.gamecategory', verbose_name='Thuộc Game')),
            ],
            options={
                'verbose_name': 'Kho Nick',
                'verbose_name_plural': 'Kho Nick',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NickOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.DecimalField(decimal_places=0, help_text='Lưu lại giá lúc mua phòng khi admin đổi giá nick sau này', max_digits=12, verbose_name='Giá lúc mua')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian mua')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.accountinventory', verbose_name='Nick đã mua')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nick_orders', to=settings.AUTH_USER_MODEL, verbose_name='Người mua')),
            ],
            options={
                'verbose_name': 'Đơn mua Nick',
                'verbose_name_plural': 'Đơn mua Nick',
                'ordering': ['-created_at'],
            },
        ),
    ]
