# Generated by Django 6.0.3 on 2026-04-07 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinventory',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Đã duyệt hiển thị'),
        ),
        migrations.AddField(
            model_name='accountinventory',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Người đăng bán'),
        ),
        migrations.AddField(
            model_name='nickorder',
            name='refund_note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú hoàn tiền'),
        ),
        migrations.AddField(
            model_name='nickorder',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn tiền'),
        ),
        migrations.AddField(
            model_name='nickorder',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Thành công'), ('CHECKING', 'Đang kiểm tra'), ('REFUNDED', 'Lỗi - Hoàn tiền')], default='SUCCESS', max_length=20, verbose_name='Trạng thái đơn'),
        ),
    ]
