# Generated by Django 6.0.3 on 2026-04-08 11:33

from django.db import migrations, models


def forwards(apps, schema_editor):
    NickOrder = apps.get_model('shop', 'NickOrder')
    AccountInventory = apps.get_model('shop', 'AccountInventory')

    status_map = {
        'SUCCESS': 'COMPLETED',
        'CHECKING': 'PENDING',
        'REFUNDED': 'CANCELLED',
    }

    for order in NickOrder.objects.select_related('account').all():
        mapped_status = status_map.get(order.status, order.status)
        if mapped_status != order.status:
            order.status = mapped_status
            order.save(update_fields=['status'])

        if order.status == 'CANCELLED':
            AccountInventory.objects.filter(pk=order.account_id).update(status='HIDDEN')
        else:
            AccountInventory.objects.filter(pk=order.account_id).update(status='SOLD')


def backwards(apps, schema_editor):
    NickOrder = apps.get_model('shop', 'NickOrder')
    AccountInventory = apps.get_model('shop', 'AccountInventory')

    status_map = {
        'COMPLETED': 'SUCCESS',
        'PENDING': 'CHECKING',
        'CANCELLED': 'REFUNDED',
    }

    for order in NickOrder.objects.select_related('account').all():
        mapped_status = status_map.get(order.status, order.status)
        if mapped_status != order.status:
            order.status = mapped_status
            order.save(update_fields=['status'])

        if order.status == 'REFUNDED':
            AccountInventory.objects.filter(pk=order.account_id).update(status='HIDDEN')
        else:
            AccountInventory.objects.filter(pk=order.account_id).update(status='SOLD')


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_accountinventory_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nickorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ duyệt'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái đơn'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
