# Generated by Django 6.0.3 on 2026-04-07 09:21

import shop_game.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_default_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Là cộng tác viên/Seller'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=shop_game.accounts.models.SafeDecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số dư'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_topup',
            field=shop_game.accounts.models.SafeDecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng nạp'),
        ),
    ]
