# Generated by Django 6.0.3 on 2026-03-25 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên nhà mạng/Loại thẻ')),
                ('code', models.CharField(help_text='VD: VIETTEL, GARENA, ZING', max_length=20, unique=True, verbose_name='Mã (Code)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='VD: 20% (Thẻ 100k khách nhận 80k)', max_digits=5, verbose_name='Chiết khấu nạp (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp thẻ',
                'verbose_name_plural': 'Nhà cung cấp thẻ',
            },
        ),
        migrations.CreateModel(
            name='CardInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Mệnh giá thẻ')),
                ('serial', models.CharField(max_length=100, verbose_name='Số Serial')),
                ('card_code', models.CharField(max_length=100, verbose_name='Mã thẻ (Pin)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Chưa bán'), ('SOLD', 'Đã bán')], default='AVAILABLE', max_length=20, verbose_name='Trạng thái')),
                ('bought_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập kho')),
                ('bought_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_cards', to=settings.AUTH_USER_MODEL, verbose_name='Người mua')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='billing.cardprovider', verbose_name='Loại thẻ')),
            ],
            options={
                'verbose_name': 'Kho thẻ cào (Để bán)',
                'verbose_name_plural': 'Kho thẻ cào (Để bán)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Mệnh giá khai báo')),
                ('real_value', models.DecimalField(decimal_places=0, default=0, help_text='Số tiền thực cộng vào web sau chiết khấu', max_digits=12, verbose_name='Thực nhận')),
                ('serial', models.CharField(max_length=100, verbose_name='Số Serial')),
                ('card_code', models.CharField(max_length=100, verbose_name='Mã thẻ (Pin)')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại/Thẻ sai')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú/Lý do lỗi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nạp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian xử lý')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.cardprovider', verbose_name='Loại thẻ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='Người nạp')),
            ],
            options={
                'verbose_name': 'Đơn nạp thẻ',
                'verbose_name_plural': 'Lịch sử Nạp thẻ',
                'ordering': ['-created_at'],
            },
        ),
    ]
