# Generated by Django 6.0.3 on 2026-04-07 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTopupTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền nạp')),
                ('transfer_content', models.CharField(max_length=255, verbose_name='Nội dung chuyển khoản')),
                ('qr_url', models.URLField(max_length=600, verbose_name='Link ảnh QR')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('SUCCESS', 'Đã cộng tiền'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_topups', to=settings.AUTH_USER_MODEL, verbose_name='Người nạp')),
            ],
            options={
                'verbose_name': 'Nạp ngân hàng',
                'verbose_name_plural': 'Nạp ngân hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Mệnh giá')),
                ('serial', models.CharField(max_length=100, verbose_name='Số seri')),
                ('card_code', models.CharField(max_length=100, verbose_name='Mã thẻ')),
                ('real_value', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thực nhận')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.cardprovider', verbose_name='Loại thẻ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người nạp')),
            ],
            options={
                'verbose_name': 'Giao dịch thẻ cào',
                'verbose_name_plural': 'Giao dịch thẻ cào',
                'ordering': ['-created_at'],
            },
        ),
    ]
