# Generated by Django 6.0.3 on 2026-03-25 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='VD: Trúng 100K, Trúng Nick VIP, Chúc may mắn lần sau', max_length=100, verbose_name='Tên phần thưởng')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/', verbose_name='Ảnh phần thưởng')),
                ('probability', models.FloatField(default=10.0, help_text='Tổng các phần thưởng trong 1 vòng quay nên là 100%', verbose_name='Tỷ lệ trúng (%)')),
                ('value', models.DecimalField(decimal_places=0, default=0, help_text='Số tiền cộng vào tài khoản nếu trúng', max_digits=10, verbose_name='Giá trị (Nếu trúng tiền)')),
            ],
            options={
                'verbose_name': 'Phần thưởng',
                'verbose_name_plural': 'Các Phần thưởng',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vòng quay')),
                ('price', models.DecimalField(decimal_places=0, default=10000, max_digits=10, verbose_name='Giá mỗi lượt quay')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wheels/', verbose_name='Ảnh vòng quay')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Vòng quay',
                'verbose_name_plural': 'Danh sách Vòng quay',
            },
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian quay')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigame.reward', verbose_name='Phần thưởng nhận được')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người chơi')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigame.wheel', verbose_name='Vòng quay')),
            ],
            options={
                'verbose_name': 'Lịch sử quay',
                'verbose_name_plural': 'Lịch sử quay',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reward',
            name='wheel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='minigame.wheel', verbose_name='Thuộc vòng quay'),
        ),
    ]
