# Generated by Django 6.0.3 on 2026-04-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spinhistory',
            name='reward',
        ),
        migrations.AddField(
            model_name='spinhistory',
            name='prize_name',
            field=models.CharField(default='', max_length=100, verbose_name='Tên phần thưởng'),
        ),
    ]
